# Generated by Django 2.1 on 2018-08-03 06:15

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180803_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='anonymous', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='lnglat',
            field=models.CharField(blank=True, help_text='위도,경도 포멧으로 받겠습니다.', max_length=50, validators=[blog.models.lnglat_validator]),
        ),
    ]
